# generated by datamodel-codegen:
#   filename:  youtube_transcripts.yaml

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class SearchMetadata(BaseModel):
    id: str = Field(..., description="Unique identifier for the search request")
    status: str = Field(..., description="Status of the search request")
    created_at: AwareDatetime = Field(
        ..., description="Timestamp when the search was created"
    )
    request_time_taken: float | None = Field(
        None, description="Time taken to make the request in seconds"
    )
    parsing_time_taken: float | None = Field(
        None, description="Time taken to parse the results in seconds"
    )
    total_time_taken: float | None = Field(
        None, description="Total time taken for the search in seconds"
    )
    request_url: str | None = Field(None, description="YouTube URL for this search")
    html_url: str | None = Field(None, description="URL to view HTML results")
    json_url: str | None = Field(None, description="URL to view JSON results")


class SearchParameters(BaseModel):
    engine: str | None = Field(None, description="Search engine used")
    video_id: str | None = Field(None, description="YouTube video ID")
    lang: str | None = Field(None, description="Language code for the transcript")
    transcript_type: str | None = Field(
        None, description="Type of transcript (auto or manual)"
    )
    transcript_name: str | None = Field(
        None, description="Exact available transcript name to retrieve"
    )
    only_available: bool | None = Field(
        None, description="Whether to fall back to the first available language"
    )


class Transcript(BaseModel):
    text: str | None = Field(None, description="The transcript text content")
    start: float | None = Field(
        None, description="Start time of this transcript segment in seconds"
    )
    duration: float | None = Field(
        None, description="Duration of this transcript segment in seconds"
    )


class AvailableLanguage(BaseModel):
    name: str | None = Field(None, description="Display name of the language")
    lang: str | None = Field(None, description="Language code")


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message describing what went wrong")


class SearchResponse(BaseModel):
    search_metadata: SearchMetadata | None = None
    search_parameters: SearchParameters | None = None
    transcripts: list[Transcript] | None = Field(
        None, description="Array of transcript segments with timing information"
    )
    available_languages: list[AvailableLanguage] | None = Field(
        None, description="List of available languages for this video's transcripts"
    )
    error: str | None = Field(
        None, description="Error message if transcripts could not be retrieved"
    )
