# generated by datamodel-codegen:
#   filename:  youtube.yaml

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class SearchMetadata(BaseModel):
    id: str = Field(..., description="Unique identifier for the search request")
    status: str = Field(..., description="Status of the search request")
    created_at: AwareDatetime = Field(
        ..., description="Timestamp when the search was created"
    )
    request_time_taken: float | None = Field(
        None, description="Time taken to make the request in seconds"
    )
    parsing_time_taken: float | None = Field(
        None, description="Time taken to parse the results in seconds"
    )
    total_time_taken: float | None = Field(
        None, description="Total time taken for the search in seconds"
    )
    request_url: str | None = Field(None, description="YouTube URL for this search")
    html_url: str | None = Field(None, description="URL to view HTML results")
    json_url: str | None = Field(None, description="URL to view JSON results")


class SearchParameters(BaseModel):
    engine: str | None = Field(None, description="Search engine used")
    q: str | None = Field(None, description="Search query that was used")
    sp: str | None = Field(
        None, description="Filter/pagination parameter that was used"
    )
    hl: str | None = Field(None, description="Interface language that was used")
    gl: str | None = Field(None, description="Country code that was used")


class SearchInformation(BaseModel):
    total_results: int | None = Field(None, description="Total number of results found")
    state: str | None = Field(
        None, description="State of query correction if applicable"
    )
    original_query: str | None = Field(
        None, description="Original query before correction"
    )
    original_query_sp: str | None = Field(
        None, description="SP parameter for original query"
    )
    corrected_query: str | None = Field(
        None, description="Corrected query if spelling fix was applied"
    )


class VideoChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    thumbnail: str | None = Field(None, description="Channel thumbnail URL")


class PlaylistChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    link: str | None = Field(None, description="Link to the channel")


class PlaylistVideo(BaseModel):
    id: str | None = Field(None, description="Video ID")
    title: str | None = Field(None, description="Video title")
    link: str | None = Field(None, description="Link to the video")
    length: str | None = Field(None, description="Video duration")


class MovieChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )


class MetadataItems(BaseModel):
    top: list[str] | None = Field(None, description="Top metadata items")
    bottom: list[str] | None = Field(None, description="Bottom metadata items")


class Short(BaseModel):
    position: int | None = Field(None, description="Position within shorts section")
    id: str | None = Field(None, description="Short video ID")
    title: str | None = Field(None, description="Short title")
    link: str | None = Field(None, description="Link to the short")
    duration: str | None = Field(None, description="Short duration")
    views: int | None = Field(None, description="Number of views")
    thumbnail: str | None = Field(None, description="Short thumbnail URL")


class PostChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    thumbnail: str | None = Field(None, description="Channel thumbnail URL")


class SectionChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")


class PeopleAlsoSearchFor(BaseModel):
    query: str | None = Field(None, description="Suggested search query")
    link: str | None = Field(None, description="Link to perform the search")
    thumbnail: str | None = Field(None, description="Thumbnail for the suggestion")


class AdChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")


class HighlightedVideo(BaseModel):
    id: str | None = Field(None, description="Video ID")
    title: str | None = Field(None, description="Video title")
    subtitle: str | None = Field(None, description="Video subtitle")
    link: str | None = Field(None, description="Link to the video")
    length: str | None = Field(None, description="Video duration")


class FeaturedVideoChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")


class KeyMoment(BaseModel):
    title: str | None = Field(None, description="Key moment title")
    start_seconds: int | None = Field(
        None, description="Start time of the moment in seconds"
    )
    thumbnail: str | None = Field(None, description="Key moment thumbnail URL")


class Thumbnail(BaseModel):
    static: str | None = Field(None, description="Static thumbnail URL")
    rich: str | None = Field(None, description="Rich/animated thumbnail URL")


class Pagination(BaseModel):
    next_page_token: str | None = Field(
        None, description="Token to fetch the next page of results"
    )


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message describing what went wrong")


class Video(BaseModel):
    position: int | None = Field(None, description="Position in search results")
    id: str | None = Field(None, description="YouTube video ID")
    title: str | None = Field(None, description="Video title")
    link: str | None = Field(None, description="Link to the video")
    description: str | None = Field(None, description="Video description snippet")
    views: int | None = Field(None, description="Number of views")
    is_live: bool | None = Field(
        None, description="Whether the video is currently live"
    )
    channel: VideoChannel | None = None
    length: str | None = Field(None, description="Video duration")
    published_time: str | None = Field(None, description="Time since publication")
    badges: list[str] | None = Field(None, description="Video badges")
    thumbnail: Thumbnail | None = None
    key_moments: list[KeyMoment] | None = Field(
        None, description="Key moments in the video"
    )


class Channel(BaseModel):
    position: int | None = Field(None, description="Position in search results")
    id: str | None = Field(None, description="YouTube channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")
    description: str | None = Field(None, description="Channel description")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    video_count: int | None = Field(None, description="Number of videos")
    subscribers: int | None = Field(None, description="Number of subscribers")
    thumbnail: Thumbnail | None = None


class Playlist(BaseModel):
    position: int | None = Field(None, description="Position in search results")
    id: str | None = Field(None, description="Playlist ID")
    title: str | None = Field(None, description="Playlist title")
    link: str | None = Field(None, description="Link to the playlist")
    video_count: int | None = Field(None, description="Number of videos in playlist")
    channel: PlaylistChannel | None = None
    published_time: str | None = Field(None, description="Time since publication")
    videos: list[PlaylistVideo] | None = Field(
        None, description="Videos in the playlist"
    )
    thumbnail: str | None = Field(None, description="Playlist thumbnail URL")


class Movie(BaseModel):
    position: int | None = Field(None, description="Position in search results")
    id: str | None = Field(None, description="Movie video ID")
    title: str | None = Field(None, description="Movie title")
    link: str | None = Field(None, description="Link to the movie")
    description: str | None = Field(None, description="Movie description")
    channel: MovieChannel | None = None
    length: str | None = Field(None, description="Movie duration")
    metadata_items: MetadataItems | None = None
    badges: list[str] | None = Field(None, description="Movie badges")
    buttons: list[str] | None = Field(None, description="Action buttons")
    thumbnail: str | None = Field(None, description="Movie thumbnail URL")


class Shorts(BaseModel):
    section_title: str | None = Field(None, description="Section title for shorts")
    position: int | None = Field(None, description="Position in search results")
    items: list[Short] | None = Field(None, description="Short videos")


class Post(BaseModel):
    position: int | None = Field(None, description="Position within posts section")
    id: str | None = Field(None, description="Post ID")
    link: str | None = Field(None, description="Link to the post")
    text: str | None = Field(None, description="Post text content")
    likes: str | None = Field(None, description="Number of likes text")
    extracted_likes: int | None = Field(None, description="Number of likes as integer")
    comments: str | None = Field(None, description="Number of comments text")
    extracted_comments: int | None = Field(
        None, description="Number of comments as integer"
    )
    channel: PostChannel | None = None
    published_time: str | None = Field(None, description="Time since publication")
    thumbnail: str | None = Field(None, description="Post thumbnail URL")


class SectionItem(BaseModel):
    id: str | None = Field(None, description="Item ID")
    title: str | None = Field(None, description="Item title")
    link: str | None = Field(None, description="Link to the item")
    channel: SectionChannel | None = None
    views: int | None = Field(None, description="Number of views")
    published_time: str | None = Field(None, description="Time since publication")
    length: str | None = Field(None, description="Item duration")
    thumbnail: str | None = Field(None, description="Item thumbnail URL")


class Ad(BaseModel):
    position: int | None = Field(None, description="Position in search results")
    id: str | None = Field(None, description="Video ID for video ads")
    title: str | None = Field(None, description="Ad title")
    link: str | None = Field(None, description="Ad link")
    description: str | None = Field(None, description="Ad description")
    website: str | None = Field(None, description="Advertiser website URL")
    channel: AdChannel | None = None
    length: str | None = Field(None, description="Video duration for video ads")
    thumbnail: str | None = Field(None, description="Ad thumbnail URL")


class FeaturedVideo(BaseModel):
    id: str | None = Field(None, description="Video ID")
    title: str | None = Field(None, description="Video title")
    subtitle: str | None = Field(None, description="Video subtitle")
    link: str | None = Field(None, description="Link to the video")
    length: str | None = Field(None, description="Video duration")
    channel: FeaturedVideoChannel | None = None
    thumbnail: str | None = Field(None, description="Video thumbnail URL")


class Posts(BaseModel):
    section_title: str | None = Field(None, description="Section title for posts")
    position: int | None = Field(None, description="Position in search results")
    items: list[Post] | None = Field(None, description="Community posts")


class Section(BaseModel):
    section_title: str | None = Field(None, description="Section title")
    position: int | None = Field(None, description="Position in search results")
    items: list[SectionItem] | None = Field(None, description="Items in the section")


class FeaturedChannel(BaseModel):
    id: str | None = Field(None, description="Featured channel ID")
    title: str | None = Field(None, description="Featured channel title")
    subtitle: str | None = Field(None, description="Featured channel subtitle")
    link: str | None = Field(None, description="Link to the featured channel")
    highlighted_video: HighlightedVideo | None = None
    videos: list[FeaturedVideo] | None = Field(
        None, description="Featured channel videos"
    )


class SearchResponse(BaseModel):
    search_metadata: SearchMetadata | None = None
    search_parameters: SearchParameters | None = None
    search_information: SearchInformation | None = None
    suggestions: list[str] | None = Field(None, description="Search query suggestions")
    ads: list[Ad] | None = Field(None, description="Advertisement results")
    channels: list[Channel] | None = Field(None, description="YouTube channel results")
    movies: list[Movie] | None = Field(None, description="Movie results")
    videos: list[Video] | None = Field(None, description="Video search results")
    playlists: list[Playlist] | None = Field(None, description="Playlist results")
    sections: list[Section] | None = Field(None, description="Section results")
    shorts: list[Shorts] | None = Field(None, description="YouTube Shorts results")
    posts: list[Posts] | None = Field(None, description="Community post results")
    people_also_search_for: list[PeopleAlsoSearchFor] | None = Field(
        None, description="Related search suggestions"
    )
    featured_channel: FeaturedChannel | None = None
    pagination: Pagination | None = None
    error: str | None = Field(None, description="Error message if the search failed")
