# generated by datamodel-codegen:
#   filename:  youtube_channel.yaml

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, Field


class SearchMetadata(BaseModel):
    id: str = Field(..., description="Unique identifier for the search request")
    status: str = Field(..., description="Status of the search request")
    created_at: AwareDatetime = Field(
        ..., description="Timestamp when the search was created"
    )
    request_time_taken: float | None = Field(
        None, description="Time taken to make the request in seconds"
    )
    parsing_time_taken: float | None = Field(
        None, description="Time taken to parse the results in seconds"
    )
    total_time_taken: float | None = Field(
        None, description="Total time taken for the search in seconds"
    )
    request_url: str | None = Field(None, description="YouTube URL for this search")
    html_url: str | None = Field(None, description="URL to view HTML results")
    json_url: str | None = Field(None, description="URL to view JSON results")


class SearchParameters(BaseModel):
    engine: str | None = Field(None, description="Search engine used")
    channel_id: str | None = Field(None, description="YouTube channel ID or handle")
    gl: str | None = Field(None, description="Country code for localized results")
    hl: str | None = Field(None, description="Language code for interface language")


class Link(BaseModel):
    title: str | None = Field(None, description="Link title")
    link: str | None = Field(None, description="URL of the external link")


class About(BaseModel):
    description: str | None = Field(None, description="Full description of the channel")
    subscribers: int | None = Field(None, description="Number of subscribers")
    videos: int | None = Field(None, description="Number of videos")
    views: int | None = Field(None, description="Total channel views")
    joined_date: date | None = Field(
        None, description="Date when the channel was created (ISO 8601 format)"
    )
    joined_date_text: str | None = Field(None, description="Human-readable joined date")
    country: str | None = Field(None, description="Country of the channel")
    links: list[Link] | None = None


class Channel(BaseModel):
    handle: str | None = Field(None, description='Channel handle (e.g., "@MrBeast")')
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel title")
    subscribers: int | None = Field(None, description="Number of subscribers")
    videos: int | None = Field(None, description="Number of videos")
    description: str | None = Field(None, description="Channel description")
    keywords: str | None = Field(None, description="Channel keywords")
    tags: list[str] | None = Field(None, description="Channel tags")
    available_countries: list[str] | None = Field(
        None, description="Countries where the channel is available"
    )
    badges: list[str] | None = Field(
        None, description='Channel badges (e.g., "Verified")'
    )
    first_link: str | None = Field(
        None, description="First external link of the channel"
    )
    banner: str | None = Field(None, description="URL of the channel banner image")
    avatar: str | None = Field(None, description="URL of the channel avatar image")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    is_family_safe: bool | None = Field(
        None, description="Whether the channel is family-safe"
    )
    is_unlisted: bool | None = Field(
        None, description="Whether the channel is unlisted"
    )
    facebook_profile_id: str | None = Field(
        None, description="Associated Facebook profile ID"
    )


class HighlightedVideo(BaseModel):
    id: str | None = Field(None, description="Video ID")
    title: str | None = Field(None, description="Video title")
    link: str | None = Field(None, description="Video URL")
    description: str | None = Field(None, description="Video description")
    external_links: list[str] | None = Field(
        None, description="External links mentioned in the video description"
    )
    views: int | None = Field(None, description="Number of views")
    published_time: str | None = Field(None, description="When the video was published")


class FeaturedChannel(BaseModel):
    handle: str | None = Field(None, description="Channel handle")
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel title")
    link: str | None = Field(None, description="Channel URL")
    description: str | None = Field(None, description="Channel description")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    subscribers: int | None = Field(None, description="Number of subscribers")


class OtherChannel(BaseModel):
    position: int | None = Field(None, description="Position in the list")
    handle: str | None = Field(None, description="Channel handle")
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel title")
    link: str | None = Field(None, description="Channel URL")
    video_count: int | None = Field(None, description="Number of videos")
    subscribers: int | None = Field(None, description="Number of subscribers")


class Video(BaseModel):
    position: int | None = Field(None, description="Position in the list")
    id: str | None = Field(None, description="Video ID")
    title: str | None = Field(None, description="Video title")
    link: str | None = Field(None, description="Video URL")
    views: int | None = Field(None, description="Number of views")
    length: str | None = Field(None, description="Video duration")
    published_time: str | None = Field(None, description="When the video was published")
    badges: list[str] | None = Field(
        None, description='Video badges (e.g., "CC", "4K")'
    )
    thumbnail: str | None = Field(None, description="URL of the video thumbnail")


class Short(BaseModel):
    position: int | None = Field(None, description="Position in the list")
    id: str | None = Field(None, description="Short video ID")
    title: str | None = Field(None, description="Short video title")
    link: str | None = Field(None, description="Short video URL")
    duration: str | None = Field(None, description="Short video duration")
    views: int | None = Field(None, description="Number of views")
    thumbnail: str | None = Field(None, description="URL of the short thumbnail")


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message describing what went wrong")


class VideosSection(BaseModel):
    section_title: str | None = Field(None, description="Title of the video section")
    videos: list[Video] | None = None


class ShortsSection(BaseModel):
    section_title: str | None = Field(None, description="Title of the shorts section")
    shorts: list[Short] | None = None


class SearchResponse(BaseModel):
    search_metadata: SearchMetadata | None = None
    search_parameters: SearchParameters | None = None
    error: str | None = Field(None, description="Error message if the search failed")
    about: About | None = None
    channel: Channel | None = None
    highlighted_video: HighlightedVideo | None = None
    featured_channel: FeaturedChannel | None = None
    other_channels: list[OtherChannel] | None = None
    videos_sections: list[VideosSection] | None = None
    shorts_sections: list[ShortsSection] | None = None
