# generated by datamodel-codegen:
#   filename:  youtube_channel_videos.yaml

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class SearchMetadata(BaseModel):
    id: str = Field(..., description="Unique identifier for the search request")
    status: str = Field(..., description="Status of the search request")
    created_at: AwareDatetime = Field(
        ..., description="Timestamp when the search was created"
    )
    request_time_taken: float | None = Field(
        None, description="Time taken to make the request in seconds"
    )
    parsing_time_taken: float | None = Field(
        None, description="Time taken to parse the results in seconds"
    )
    total_time_taken: float | None = Field(
        None, description="Total time taken for the search in seconds"
    )
    request_url: str | None = Field(None, description="YouTube URL for this search")
    html_url: str | None = Field(None, description="URL to view HTML results")
    json_url: str | None = Field(None, description="URL to view JSON results")


class SearchParameters(BaseModel):
    engine: str | None = Field(None, description="The search engine used")
    channel_id: str | None = Field(None, description="The YouTube channel ID or handle")
    gl: str | None = Field(None, description="Country code used for the search")
    hl: str | None = Field(None, description="Language code used for the search")
    next_page_token: str | None = Field(
        None, description="Pagination token used for this request"
    )


class Channel(BaseModel):
    handle: str | None = Field(None, description='Channel handle (e.g., "@MrBeast")')
    id: str | None = Field(None, description="Unique channel identifier")
    title: str | None = Field(None, description="Channel name")
    subscribers: int | None = Field(None, description="Number of channel subscribers")
    videos: int | None = Field(
        None, description="Total number of videos on the channel"
    )
    description: str | None = Field(None, description="Channel description")
    keywords: str | None = Field(None, description="Channel keywords")
    tags: list[str] | None = Field(None, description="Channel tags")
    available_countries: list[str] | None = Field(
        None, description="Countries where the channel is available"
    )
    facebook_profile_id: str | None = Field(
        None, description="Associated Facebook profile ID"
    )
    badges: list[str] | None = Field(
        None, description="Channel badges and certifications"
    )
    first_link: str | None = Field(
        None, description="Primary external link for the channel"
    )
    is_unlisted: bool | None = Field(
        None, description="Whether the channel is unlisted"
    )
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    is_family_safe: bool | None = Field(
        None, description="Whether the channel is family-safe"
    )
    banner: str | None = Field(None, description="URL to channel banner image")
    avatar: str | None = Field(None, description="URL to channel avatar image")


class VideoChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="Link to the channel")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    thumbnail: str | None = Field(None, description="URL to channel thumbnail")


class VideoThumbnail(BaseModel):
    static: str | None = Field(None, description="URL to static thumbnail image")
    rich: str | None = Field(None, description="URL to rich/animated thumbnail")


class KeyMoment(BaseModel):
    title: str | None = Field(None, description="Title of the key moment")
    start_seconds: int | None = Field(
        None, description="Start time of the moment in seconds"
    )
    thumbnail: str | None = Field(None, description="URL to moment thumbnail")


class PaginationFilter(BaseModel):
    text: str | None = Field(None, description="Filter display text")
    next_page_token: str | None = Field(None, description="Token to apply this filter")


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message describing what went wrong")


class Video(BaseModel):
    position: int | None = Field(None, description="Position in the search results")
    id: str | None = Field(None, description="YouTube video ID")
    title: str | None = Field(None, description="Video title")
    link: str | None = Field(None, description="Direct link to the video")
    description: str | None = Field(None, description="Video description snippet")
    views: int | None = Field(None, description="Number of video views")
    is_live: bool | None = Field(
        None, description="Whether the video is currently live"
    )
    channel: VideoChannel | None = None
    length: str | None = Field(None, description='Video duration (e.g., "12:34")')
    published_time: str | None = Field(
        None, description='Relative time since publication (e.g., "2 days ago")'
    )
    badges: list[str] | None = Field(
        None, description='Video badges (e.g., "LIVE", "CC", "4K")'
    )
    thumbnail: VideoThumbnail | None = None
    key_moments: list[KeyMoment] | None = Field(
        None, description="Key moments or chapters in the video"
    )


class Pagination(BaseModel):
    filters: list[PaginationFilter] | None = Field(
        None,
        description="Available filter options (only present in initial requests, not in paginated requests)",
    )
    next_page_token: str | None = Field(
        None, description="Token to retrieve the next page of results"
    )


class SearchResponse(BaseModel):
    search_metadata: SearchMetadata | None = None
    search_parameters: SearchParameters | None = None
    channel: Channel | None = Field(
        None,
        description="Channel information (only present in initial requests, not in paginated requests)",
    )
    videos: list[Video] | None = None
    pagination: Pagination | None = None
    error: str | None = Field(None, description="Error message if the search failed")
