# generated by datamodel-codegen:
#   filename:  youtube_comments.yaml

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class SearchMetadata(BaseModel):
    id: str = Field(..., description="Unique identifier for the search request")
    status: str = Field(..., description="Status of the search request")
    created_at: AwareDatetime = Field(
        ..., description="Timestamp when the search was created"
    )
    request_time_taken: float | None = Field(
        None, description="Time taken to make the request in seconds"
    )
    parsing_time_taken: float | None = Field(
        None, description="Time taken to parse the results in seconds"
    )
    total_time_taken: float | None = Field(
        None, description="Total time taken for the search in seconds"
    )
    request_url: str | None = Field(None, description="YouTube URL for this search")
    html_url: str | None = Field(None, description="URL to view HTML results")
    json_url: str | None = Field(None, description="URL to view JSON results")


class SearchParameters(BaseModel):
    engine: str | None = Field(None, description="Search engine used")
    video_id: str | None = Field(None, description="YouTube video ID")
    gl: str | None = Field(None, description="Country code used for the search")
    hl: str | None = Field(None, description="Language code used for the search")
    next_page_token: str | None = Field(None, description="Token used for pagination")


class SearchInformation(BaseModel):
    total_results: int | None = Field(
        None, description="Total number of comments for the video"
    )


class Channel(BaseModel):
    id: str = Field(..., description="Channel ID")
    handle: str = Field(..., description="Channel handle or display name")
    link: str = Field(..., description="Link to the channel on YouTube")
    thumbnail: str = Field(..., description="URL of the channel thumbnail image")


class Pagination(BaseModel):
    next_page_token: str | None = Field(
        None, description="Token to retrieve the next page of comments"
    )
    replies_next_page_token: str | None = Field(
        None, description="Token to retrieve the next page of replies"
    )


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message describing what went wrong")


class Comment(BaseModel):
    id: str = Field(..., description="Unique identifier for the comment")
    link: str = Field(..., description="Direct link to the comment on YouTube")
    channel: Channel
    published_date: str = Field(..., description="Publication date of the comment")
    text: str = Field(..., description="Content of the comment")
    likes: int = Field(..., description="Number of likes on the comment")
    replies: int | None = Field(None, description="Number of replies to the comment")
    replies_next_page_token: str | None = Field(
        None, description="Token to retrieve replies for this comment"
    )


class SearchResponse(BaseModel):
    search_metadata: SearchMetadata | None = None
    search_parameters: SearchParameters | None = None
    search_information: SearchInformation | None = None
    comments: list[Comment] | None = Field(None, description="Array of comment objects")
    pagination: Pagination | None = None
    error: str | None = Field(
        None, description="Error message when comments cannot be retrieved"
    )
