# generated by datamodel-codegen:
#   filename:  youtube_video.yaml

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class SearchMetadata(BaseModel):
    id: str = Field(..., description="Unique identifier for the search request")
    status: str = Field(..., description="Status of the search request")
    created_at: AwareDatetime = Field(
        ..., description="Timestamp when the search was created"
    )
    request_time_taken: float | None = Field(
        None, description="Time taken to make the request in seconds"
    )
    parsing_time_taken: float | None = Field(
        None, description="Time taken to parse the results in seconds"
    )
    total_time_taken: float | None = Field(
        None, description="Total time taken for the search in seconds"
    )
    request_url: str | None = Field(None, description="YouTube URL for this search")
    html_url: str | None = Field(None, description="URL to view HTML results")
    json_url: str | None = Field(None, description="URL to view JSON results")


class SearchParameters(BaseModel):
    engine: str | None = Field(None, description="The engine used for the search")
    video_id: str | None = Field(None, description="The YouTube video ID")
    gl: str | None = Field(None, description="Country code used for the search")
    hl: str | None = Field(None, description="Language code used for the search")


class VideoFormat(BaseModel):
    itag: int | None = Field(None, description="Format tag identifier")
    mime_type: str | None = Field(None, description="MIME type of the format")
    bitrate: int | None = Field(None, description="Bitrate of the format")
    width: int | None = Field(None, description="Video width in pixels")
    height: int | None = Field(None, description="Video height in pixels")
    last_modified_unix: str | None = Field(
        None, description="Unix timestamp of last modification"
    )
    last_modified: str | None = Field(
        None, description='Last modification timestamp (e.g. "2025-12-28 23:11:32 UTC")'
    )
    content_length: str | None = Field(None, description="Content length in bytes")
    quality: str | None = Field(None, description="Quality descriptor")
    fps: int | None = Field(None, description="Frames per second")
    quality_label: str | None = Field(
        None, description="Quality label (e.g., 1080p, 720p)"
    )
    projection_type: str | None = Field(None, description="Video projection type")


class FeaturedChannel(BaseModel):
    id: str | None = Field(None, description="Featured channel ID")
    name: str | None = Field(None, description="Featured channel name")
    link: str | None = Field(None, description="URL to the featured channel")


class Comment(BaseModel):
    total: int | None = Field(None, description="Total number of comments")


class KeyMoment(BaseModel):
    title: str | None = Field(None, description="Key moment title")
    start_seconds: int | None = Field(None, description="Start time in seconds")
    thumbnail: str | None = Field(None, description="URL of the key moment thumbnail")


class Chapter(BaseModel):
    title: str | None = Field(None, description="Chapter title")
    timestamp: str | None = Field(None, description="Chapter timestamp")
    thumbnail: str | None = Field(None, description="URL of the chapter thumbnail")


class TranscriptLanguage(BaseModel):
    name: str | None = Field(None, description="Language name")
    lang: str | None = Field(None, description="Language code")


class RecommendedVideoChannel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    title: str | None = Field(None, description="Channel title")
    link: str | None = Field(None, description="URL to the channel")
    is_verified: bool | None = Field(
        None, description="Whether the channel is verified"
    )
    thumbnail: str | None = Field(None, description="URL of the channel thumbnail")


class RecommendedPlaylist(BaseModel):
    position: int | None = Field(
        None, description="Position in the recommendations list"
    )
    id: str | None = Field(None, description="Playlist ID")
    title: str | None = Field(None, description="Playlist title")
    link: str | None = Field(None, description="URL to the playlist")
    video_count: int | None = Field(
        None, description="Number of videos in the playlist"
    )
    description: str | None = Field(None, description="Playlist description")
    published_time: str | None = Field(
        None, description="When the playlist was published"
    )
    thumbnail: str | None = Field(None, description="URL of the playlist thumbnail")


class CommentsSortingTokenItem(BaseModel):
    title: str | None = Field(None, description="Sorting option title")
    next_page_token: str | None = Field(
        None, description="Token for this sorting option"
    )


class Pagination(BaseModel):
    comments_next_page_token: str | None = Field(
        None, description="Token for next page of comments"
    )
    comments_sorting_token: list[CommentsSortingTokenItem] | None = None
    recommended_videos_next_page_token: str | None = Field(
        None, description="Token for next page of recommended videos"
    )


class MerchantItem(BaseModel):
    title: str | None = Field(None, description="Item title")
    link: str | None = Field(None, description="URL to the item")
    description: str | None = Field(None, description="Item description")
    price: str | None = Field(None, description="Item price")
    extracted_price: float | None = Field(
        None, description="Extracted numeric price value"
    )
    seller: str | None = Field(None, description="Seller name")
    seller_text: str | None = Field(None, description="Additional seller text")
    availability: str | None = Field(None, description="Item availability status")
    thumbnail: str | None = Field(None, description="URL of the item thumbnail")


class Context(BaseModel):
    title: str | None = Field(None, description="Context title")
    link: str | None = Field(None, description="URL to the context source")
    source: str | None = Field(None, description="Context source")
    snippet: str | None = Field(None, description="Context snippet text")
    thumbnail: str | None = Field(None, description="URL of the context thumbnail")


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message describing what went wrong")


class Video(BaseModel):
    id: str | None = Field(None, description="YouTube video ID")
    title: str | None = Field(None, description="Video title")
    length_seconds: int | None = Field(None, description="Video duration in seconds")
    views: int | None = Field(None, description="Number of views")
    likes: int | None = Field(None, description="Number of likes")
    author: str | None = Field(None, description="Video author/creator name")
    category: str | None = Field(None, description="Video category")
    published_time: str | None = Field(None, description="When the video was published")
    description: str | None = Field(None, description="Video description")
    keywords: list[str] | None = Field(None, description="Video keywords/tags")
    is_owner_viewing: bool | None = Field(
        None, description="Whether the owner is viewing the video"
    )
    is_private: bool | None = Field(None, description="Whether the video is private")
    is_unplugged_corpse: bool | None = Field(
        None, description="Whether the video is unplugged corpus"
    )
    is_live_content: bool | None = Field(
        None, description="Whether the video is live content"
    )
    is_family_safe: bool | None = Field(
        None, description="Whether the video is family safe"
    )
    thumbnail: str | None = Field(None, description="URL of the video thumbnail")
    formats: list[VideoFormat] | None = None


class Channel(BaseModel):
    id: str | None = Field(None, description="Channel ID")
    name: str | None = Field(None, description="Channel name")
    link: str | None = Field(None, description="URL to the channel")
    subscribers: int | None = Field(None, description="Number of subscribers")
    featured_channel: FeaturedChannel | None = None
    thumbnail: str | None = Field(None, description="URL of the channel thumbnail")


class RecommendedVideo(BaseModel):
    position: int | None = Field(
        None, description="Position in the recommendations list"
    )
    id: str | None = Field(None, description="Video ID")
    title: str | None = Field(None, description="Video title")
    link: str | None = Field(None, description="URL to the video")
    views: int | None = Field(None, description="Number of views")
    is_live: bool | None = Field(None, description="Whether the video is live")
    channel: RecommendedVideoChannel | None = None
    length: str | None = Field(None, description="Video duration")
    published_time: str | None = Field(None, description="When the video was published")
    badges: list[str] | None = Field(None, description="Video badges (e.g., LIVE, NEW)")
    thumbnail: str | None = Field(None, description="URL of the video thumbnail")


class RecommendedVideos(BaseModel):
    videos: list[RecommendedVideo] | None = None
    playlists: list[RecommendedPlaylist] | None = None


class SearchResponse(BaseModel):
    search_metadata: SearchMetadata | None = None
    search_parameters: SearchParameters | None = None
    video: Video | None = None
    channel: Channel | None = None
    comment: Comment | None = None
    key_moments: list[KeyMoment] | None = None
    chapters: list[Chapter] | None = None
    available_transcripts_languages: list[TranscriptLanguage] | None = None
    recommended_videos: RecommendedVideos | None = None
    pagination: Pagination | None = None
    merchant_items: list[MerchantItem] | None = None
    context: Context | None = None
    error: str | None = Field(
        None, description="Error message when video details cannot be retrieved"
    )
